### ISSUE TITLE
Add a `copy to clipboard` button

### ISSUE THREAD

**Issue by jordiferrero** [joshburnett/addcopyfighandler#1]
Hi @joshburnett,
Thank you so much for your package! Since 2013 we were waiting for it.

Would if be difficult to add a button in the toolbar of the UI that opens when you command `plt.plot()`. 

Thank you.

**Comment by joshburnett** [comment]
Glad you find it useful!

I understand the desire for a 'Copy' button in the figure UI, and think that would be an improvement. Unfortunately, the buttons in the figure UI are created by the matplotlib backend in use (Qt4, Qt5, tk, wx, etc), and each of those backends use a different API for adding buttons. I don't currently have any code in the module that detects which backend is in use and works accordingly, and adding such code would frankly be a fair amount of work.  The Ctrl+C keyboard shortcut works well enough for me, so I'm not strongly motivated to take that project on myself right now. :-)

I'm open to proposals via pull requests, though!
