### ISSUE TITLE
Not able to install using PIP

### ISSUE THREAD

**Issue by Axuni** [joshburnett/addcopyfighandler#10]
Hi, it seems I am having an issue installing.
Windows 8, Python 3.7, PIP 21.1.1

ERROR: Could not find a version that satisfies the requirement addconpyfighandler
ERROR: No matching distribution found for addconpyfighandler

Any suggestions? Thanks!

**Comment by joshburnett** [comment]
Looks like you have a typo in there, with an extra ‘n’ sneaking its way into ‘addcopyfighandler.’

**Comment by Axuni** [comment]
Wow.. awful mistake from my side. Sorry!
But thanks a lot for checking it!

**Comment by joshburnett** [comment]
No problem, glad to help! Glad the library is helpful for you.
