### ISSUE TITLE
Can i copy fig as emf or wmf

### ISSUE THREAD

**Issue by Korbinhu** [joshburnett/addcopyfighandler#11]
It is so exciting that the author makes this useful module, which can help us to work more efficiently. Recently, I notice that the author add PIL to support more figure formats than before. However, as a student, it is more convenient for me to use Microsoft Word and Microsoft-PPT to handle scientific papers, and my question is that can I copy Matplotlib figures as WMF or EMF to the clipboard? If yes, how to use this module, could you give some examples? If not, do you have any plan to deal with it? 
Thank you so much!

**Comment by joshburnett** [comment]
I'm glad you find the module useful!

WMF and EMF are not supported, but the copied format is determined by the value of `matplotlib.rcParams['savefig.format']`. If you set `matplotlib.rcParams['savefig.format'] = 'svg'`, the figure will be copied as an SVG, which you can then paste into Word or PowerPoint, avoiding the pixelation that can come with pasting as a bitmap.
