### ISSUE TITLE
vector graphic instead of bitmap to clipboard

### ISSUE THREAD

**Issue by OrtnerMichael** [joshburnett/addcopyfighandler#13]
Hi guys,

I love your extension - your are saving me tons of time with this !!!

any chance that you can copy the svg to the clipboard rather than a bitmap ?

sincerely,
michael

**Comment by joshburnett** [comment]
Glad it's helpful to you, Michael! SVG output is currently supported in Windows, but not Linux. Just set `matplotlib.rcParams['savefig.format'] = 'svg'` and it'll put an SVG on the clipboard.
