### ISSUE TITLE
ValueError: Unsupported matplotlib backend (qtagg) on this OS (= MacOS)

### ISSUE THREAD

**Issue by shuntaraw** [joshburnett/addcopyfighandler#16]
The backend in `matplotlib.use("backend")` is case sensitive on macOS 14.4.

```
>>> import matplotlib 
>>> import matplotlib.pyplot as plt
>>> matplotlib.use("qtagg")
>>> print(plt.get_backend())
qtagg
>>> matplotlib.use("Qtagg")
>>> print(plt.get_backend())
Qtagg
```

As the result, the condition`'Qt' in backend:` is not met in https://github.com/joshburnett/addcopyfighandler/blob/master/src/addcopyfighandler.py#L140 

The issue occurs only on Apple Silicon, and not Intel CPU. Not sure if it is related.

**Comment by joshburnett** [comment]
Fixed in 3.2.1.
