### ISSUE TITLE
Second figure not copied 

### ISSUE THREAD

**Issue by shuntaraw** [joshburnett/addcopyfighandler#19]
The figure is not copied in the window except the first.

```
import matplotlib.pyplot as plt
import addcopyfighandler

plt.figure(1)
plt.plot()
plt.figure(2)
plt.plot()

plt.show()
```

This code opens 2 windows `Figure 1` and `Figure 2`. `Figure copied.` message is printed to console only when pressing Cmd+C in window 1, but not in window 2. 

Environment:
- MacOS 14.4
- Python 3.9.6
- addcopyfighandler 3.2.2
- PyQt5 5.15.11

**Comment by joshburnett** [comment]
Thanks for the reports. What version of matplotlib are each of you using?

**Comment by shuntaraw** [comment]
My matplotlib is version 3.9.2. The script was run from python interactive shell i.e. type `python` in `Terminal.app` and copy-paste the above code.

**Comment by Entropy512** [comment]
Matplotlib 3.9.0 here, Python 3.12.3 on Ubuntu 24.04

**Comment by joshburnett** [comment]
Alright, I believe I fixed the issue. I wasn't quite handling the event registration correctly. It definitely works in Windows now, but I haven't had a chance to test it on MacOS or LInux yet. Any chance you can try out the code in [this branch](https://github.com/joshburnett/addcopyfighandler/tree/19-second-figure-not-copied)?

**Comment by shuntaraw** [comment]
Fix confirmed on MacOS. Thanks!

**Comment by joshburnett** [comment]
Fixed, new release is now up on PyPI.
