### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_window_title'

### ISSUE THREAD

**Issue by abedhammoud** [joshburnett/addcopyfighandler#20]
I just updated to the latest version of addcopyfighandler, and now I am getting the following error when I use copyfig.

```python
addcopyfighandler.copyfig(mplfig)
   File "C:\Users\abed\miniconda3\envs\adev\Lib\site-packages\addcopyfighandler.py", line 108, in copyfig
     fig_window_text = fig.canvas.manager.get_window_title()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'get_window_title'



```

**Comment by joshburnett** [comment]
What OS and graphics backend are you using?

**Comment by abedhammoud** [comment]
I am using win11, and `get_backend()` returns `Agg`

Please see my code. Very simple:
```python
def copy_mpl_figure_to_clipboard(mplfig: mpl.figure.Figure) -> None:
    """Copy a Matplotlib figure to the clipboard.

    This function uses the addcopyfighandler module to copy a Matplotlib figure
    to the clipboard, allowing it to be pasted into other applications.

    Parameters
    ----------
    mplfig : mpl.figure.Figure
        The Matplotlib figure to be copied to the clipboard.

    Returns
    -------
    None

    """
    logger.debug(f'Copying figure to clipboard...backend={mpl.get_backend()}')
    addcopyfighandler.copyfig(mplfig)
```

I went back to version addcopyfighandler == 3.2.2 and all works ok.

**Comment by joshburnett** [comment]
Are you using PySide2, PySide6, PyQt5, PyQt6, or Tk as the backend? And what version of matplotlib?

**Comment by joshburnett** [comment]
Are you manually setting 'Agg' to be the backend? The [matplotlib docs](https://matplotlib.org/stable/users/explain/figure/backends.html) seem to indicate that Agg isn't really used on Windows, and that it's to be used non-interactively:

> Without a backend explicitly set, Matplotlib automatically detects a usable backend based on what is available on your system and on whether a GUI event loop is already running. The first usable backend in the following list is selected: MacOSX, QtAgg, GTK4Agg, Gtk3Agg, TkAgg, WxAgg, Agg. **The last, Agg, is a non-interactive backend that can only write to files. It is used on Linux, if Matplotlib cannot connect to either an X display or a Wayland display.**

**Comment by joshburnett** [comment]
Can you check and see if this branch fixes the problem for you? https://github.com/joshburnett/addcopyfighandler/tree/20-attributeerror-nonetype-object-has-no-attribute-get_window_title

**Comment by abedhammoud** [comment]
I added the following to my pyproject.toml to install the above branch, but pip is giving me an error. 

```python
# "addcopyfighandler @ https://github.com/joshburnett/addcopyfighandler/tree/20-attributeerror-nonetype-object-has-no-attribute-get_window_title"
```

Also, with or without the following code at the beginning of my app, I get the same error:
```python
# Print the current matplotlib backend
logging.warning(f'>> default matplotlib backend: {mpl.get_backend()}')
mpl.use('Qt5Agg', force=True)
logging.warning(f'>> setting backend to: {mpl.get_backend()}')
```

I am running python 3.12.5 and matplotlib 3.92, and kivy 2.3.0 Please let me know if I can give you more info. thanks.

**Comment by joshburnett** [comment]
Are you using PySide2, PySide6, PyQt5, PyQt6, or Tk as the backend? Or are you specifically selecting the 'Agg' backend?

I'm unable to make the 'Agg' backend get selected on Windows without me specifically selecting it.

**Comment by abedhammoud** [comment]
Not that I am aware of. I am using `addcopyfighandler` to copy matplotlib images that are generated by the `kivy-matplotlib-widget` library. one of the matplotlib settings that this library suggest is: 
```python
# optimized draw on Agg backend
mpl.rcParams['agg.path.chunksize'] = 1000
```
so perhaps it is changing my backend. If I could install the branch above I could do some further testing. Thanks.

**Comment by joshburnett** [comment]
Ahh, so that's where the Agg backend is being selected.

Try this:

`pip install git+https://github.com/joshburnett/addcopyfighandler.git@20-attributeerror-nonetype-object-has-no-attribute-get_window_title`

**Comment by abedhammoud** [comment]
works perfect, thanks

**Comment by abedhammoud** [comment]
3.2.4 solved my problem. Thanks.

**Comment by joshburnett** [comment]
Great! I'll get that update released.

**Comment by abedhammoud** [comment]
I am having the same issue on my Ubuntu Linux box. The backend is Agg. Sorry I should have tested this too before closing the issue earlier.

**Comment by joshburnett** [comment]
Can you post the traceback for the error on Linux? I don't see what line could be generating that error.

**Comment by abedhammoud** [comment]
Thanks Josh, I am traveling at the moment. Will do as soon as I am back. Many thanks.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abedhammoud** [comment]
when I ```import addcopyfighandler``` on my linux box , I get:
```python
________________ ERROR collecting test/utils/test_imagetools.py ________________
test/utils/test_imagetools.py:13: in <module>
    from alant.utils.imagetools import save_image_from_clipboard
src/alant/utils/imagetools.py:13: in <module>
    import addcopyfighandler
/home/abed/miniconda3/envs/adev/lib/python3.12/site-packages/addcopyfighandler.py:278: in <module>
    raise ValueError(f'Unsupported matplotlib backend ({backend}) on this OS.')
E   ValueError: Unsupported matplotlib backend (tkagg) on this OS.
```

Another part of my code, i get the similar message:

```python
File "/home/abed/miniconda3/envs/adev/lib/python3.12/site-packages/addcopyfighandler.py", line 278, in <module>
     raise ValueError(f'Unsupported matplotlib backend ({backend}) on this OS.')
 ValueError: Unsupported matplotlib backend (tkagg) on this OS.
```
please let me know if you want to send more details.

**Comment by joshburnett** [comment]
Ok, got it. The only backends that are supported on Linux are GTK 3.0 and Qt. TkAgg doesn’t offer an easy way to copy the image to the system clipboard, so it’s not supported by addcopyfighandler. If you can figure out how to get it to work, I’m happy to accept a PR!
