### ISSUE TITLE
"No matching distribution found for pywin32" when installing on ubuntu

### ISSUE THREAD

**Issue by Klemet** [joshburnett/addcopyfighandler#4]
Hello there !

Thanks a bunch for your package; it's absolutly wonderful and incredibly useful : ) !

Now that i'm on linux though, I'm having trouble making it work. It seems like it relies on libraries and packages that are only usable on windows, as when I try to install the latest version via pip install on Ubuntu, it returns : 

```
ERROR: Could not find a version that satisfies the requirement pywin32 (from addcopyfighandler) (from versions: none)
ERROR: No matching distribution found for pywin32 (from addcopyfighandler)
```

I'm able to install version 1.0 by using `pip install "addcopyfighandler==1.0" `; but then, when I try to load the module in python, it returns the following error : 

```
  File "<ipython-input-1-3ca9fbd23a4c>", line 1, in <module>
    import addcopyfighandler # Make it possible to copy a matplotlib figure to clipboard with ctrl+c

  File "/home/klemet/anaconda3/lib/python3.7/site-packages/addcopyfighandler.py", line 12, in <module>
    from win32gui import GetWindowText, GetForegroundWindow

ModuleNotFoundError: No module named 'win32gui'
```

Therefore, I'd just like to know if there is a way to use your package on linux, or if this is indeed impossible. Thank you in advance !

**Comment by joshburnett** [comment]
Glad you've found it helpful!

Unfortunately, it does not currently support Linux, as the code for putting items on the clipboard is Windows-centric. I'm pretty sure that Linux support is definitely possible, I just don't have a Linux machine available to test it on. Pull requests adding such a feature (or macOS support) would be welcome!

**Comment by Klemet** [comment]
Thank you for the precision, Josh : ) ! If I find a way to do such a thing, I'll let you know !
