### ISSUE TITLE
v2.1.0 broken for me

### ISSUE THREAD

**Issue by LiorAvrahami** [joshburnett/addcopyfighandler#8]
it seems version 2.1.0 is somewhat broken for me.

the test I'm running is:
```python
import matplotlib.pyplot as plt
import addcopyfighandler

print(addcopyfighandler.__version__)
plt.plot([1,0],[1,0])
plt.show()
```

and after pressing ctrl+c, pasting doesn't work at the right places anywhere. here is a comparative table, + means past works, - means past doesn't work:
|app for pasting|v2.0|v2.1|
|:-:|:-:|:-:|
|word|+|+|
|paint|+|-|
|markdown monster|+|-|
|file explorer|-|-|

**Comment by joshburnett** [comment]
Thanks for pointing this out.  It seems that MS Paint doesn't handle as wide a range of image data types as other applications (paint.net was working just fine, for instance).

Nevertheless, to work with as wide a number of applications as possible, I changed the behavior in 3.0 (just released) to go back to the 2.0 way of generating the clipboard image if you have PIL or pillow installed. Without PIL/pillow, it will continue working as 2.1 did.
