### ISSUE TITLE
ImportError: DLL load failed while importing win32gui

### ISSUE THREAD

**Issue by moux233** [joshburnett/addcopyfighandler#9]
First of all, thank you for this very nice feature, I love addcopyfighandler.

My bug happens with a newly created conda env, python 3.9
import addcopyfighandler fails
addcopyfighandler 2.0.0
matplotlib 3.3.4

import addcopyfighandler
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f95ac5ade708> in <module>
----> 1 import addcopyfighandler

c:\users\my_name\miniconda3\envs\qtest\lib\site-packages\addcopyfighandler.py in <module>
     12
     13 import matplotlib.pyplot as plt
---> 14 from win32gui import GetWindowText, GetForegroundWindow
     15 from PIL import Image
     16 import win32clipboard

ImportError: DLL load failed while importing win32gui: Le module spécifié est introuvable.

I found many similar issues in other packages. I installed pywin32 and the bug vanished.

**Comment by joshburnett** [comment]
Hmm, I'm not sure what happened there. I looked, and the setup.py for 2.0.0 had pywin32 listed as a dependency, so it should have been installed automatically when you installed via pip.

I just released 3.0.0, which adds support for Linux as well.  As part of that, I tested to make sure that pywin32 is installed properly (on Windows).  I'm closing this ticket, but please let me know if you run into the issue again.  I'm glad you find the module useful!

**Comment by Clemrmd** [comment]
Hi,
I get the same error when I import the module in Spyder ide
Python 3.9.12
Spyder 5.3.1

No problem when I import the module in the Anaconda prompt

The module pywin32 seems installed properly
